{"level":"error","message":"提取原图片时出错: Command failed: python E:\\Code\\WSI\\BackEnd\\algorithm\\utils\\extractPng.py --slide_folder \"E:/Downloads/slides\" --slide_file_name \"2105274011_221716.svs\"\npython: can't open file 'E:\\Code\\WSI\\BackEnd\\algorithm\\utils\\extractPng.py': [Errno 2] No such file or directory\n","timestamp":"2025-04-30 11:50:31"}
{"level":"error","message":"提取原图片时出错: Command failed: python E:\\Code\\WSI\\BackEnd\\algorithm\\utils\\extractPng.py --slide_folder \"E:/Downloads/slides\" --slide_file_name \"2105274011_221716.svs\"\npython: can't open file 'E:\\Code\\WSI\\BackEnd\\algorithm\\utils\\extractPng.py': [Errno 2] No such file or directory\n","timestamp":"2025-04-30 12:09:28"}
{"level":"error","message":"提取原图片时出错: Command failed: python E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py --slide_folder \"E:/Downloads/slides\" --slide_file_name \"2105274011_221716.svs\"\nTraceback (most recent call last):\r\n  File \"E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py\", line 6, in <module>\r\n    from utils.myLogger import setup_logger\r\nModuleNotFoundError: No module named 'utils'\r\n","timestamp":"2025-04-30 12:11:45"}
{"level":"error","message":"提取原图片时出错: Command failed: python E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py --slide_folder \"E:/Downloads/slides\" --slide_file_name \"2105274011_221716.svs\"\nTraceback (most recent call last):\r\n  File \"E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py\", line 6, in <module>\r\n    from algorithm.utils.myLogger import setup_logger\r\nModuleNotFoundError: No module named 'algorithm'\r\n","timestamp":"2025-04-30 12:13:10"}
{"level":"error","message":"提取原图片时出错: Command failed: python E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py --slide_folder \"E:/Downloads/slides\" --slide_file_name \"2105274011_221716.svs\"\nTraceback (most recent call last):\r\n  File \"E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py\", line 6, in <module>\r\n    from ..utils.myLogger import setup_logger\r\nImportError: attempted relative import with no known parent package\r\n","timestamp":"2025-04-30 12:13:33"}
{"level":"error","message":"提取原图片时出错: Command failed: python E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py --slide_folder \"E:/Downloads/slides\" --slide_file_name \"2105274011_221716.svs\"\nTraceback (most recent call last):\r\n  File \"E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py\", line 8, in <module>\r\n    from utils.myLogger import setup_logger\r\nModuleNotFoundError: No module named 'utils'\r\n","timestamp":"2025-04-30 13:23:08"}
{"level":"error","message":"提取原图片时出错: Command failed: python E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py --slide_folder \"E:/Downloads/slides\" --slide_file_name \"2105274011_221716.svs\"\nTraceback (most recent call last):\r\n  File \"E:\\Code\\WSI\\BackEnd\\algorithm\\src\\extractPng.py\", line 9, in <module>\r\n    from utils.myLogger import setup_logger\r\nModuleNotFoundError: No module named 'utils'\r\n","timestamp":"2025-04-30 13:24:04"}
